potato = Plant.find_or_create_by(name: "Potato", days_to_grow: 6, price: 50, sells_for: 120)
garlic = Plant.find_or_create_by(name: "Garlic", days_to_grow: 4, price: 40, sells_for: 90)
green_bean = Plant.find_or_create_by(name: "Green Bean", days_to_grow: 10, price: 60, sells_for: 200)
kale = Plant.find_or_create_by(name: "Kale", days_to_grow: 6, price: 70, sells_for: 165)
parsnip = Plant.find_or_create_by(name: "Parsnip", days_to_grow: 4, price: 20, sells_for: 52)
strawberry = Plant.find_or_create_by(name: "Strawberry", days_to_grow: 8, price: 50, sells_for: 180)
hot_pepper = Plant.find_or_create_by(name: "Hot Pepper", days_to_grow: 5, price: 40, sells_for: 90)
melon = Plant.find_or_create_by(name: "Melon", days_to_grow: 12, price: 110, sells_for: 300)
red_cabbage = Plant.find_or_create_by(name: "Red Cabbage", days_to_grow: 9, price: 90, sells_for: 260)
starfruit = Plant.find_or_create_by(name: "Starfruit", days_to_grow: 13, price: 450, sells_for: 1100)
wheat = Plant.find_or_create_by(name: "Wheat", days_to_grow: 2, price: 10, sells_for: 20)

yam = Plant.find_or_create_by(name: "Yam", days_to_grow: 3, price: 30, sells_for: 50)
pumpkin = Plant.find_or_create_by(name: "Pumpkin", days_to_grow: 12, price: 100, sells_for: 220)
egg_plant = Plant.find_or_create_by(name: "Egg Plant", days_to_grow: 5, price: 20, sells_for: 30)
bok_choy = Plant.find_or_create_by(name: "Bok Choy", days_to_grow: 3, price: 50, sells_for: 120)
beet = Plant.find_or_create_by(name: "Beet", days_to_grow: 7, price: 60, sells_for: 90)
ancient_fruit = Plant.find_or_create_by(name: "Ancient Fruit", days_to_grow: 15, price: 550, sells_for: 1400)


jeff = Farmer.find_or_create_by(name: "jeff", abducted: true)
jacob = Farmer.find_or_create_by(name: "jacob")
