potato = Plant.create(name: "Potato", days_to_grow: 6, price: 50, sells_for: 120)
garlic = Plant.create(name: "Garlic", days_to_grow: 4, price: 40, sells_for: 90)
green_bean = Plant.create(name: "Green Bean", days_to_grow: 10, price: 60, sells_for: 200)
kale = Plant.create(name: "Kale", days_to_grow: 6, price: 70, sells_for: 165)
parsnip = Plant.create(name: "Parsnip", days_to_grow: 4, price: 20, sells_for: 52)
strawberry = Plant.create(name: "Strawberry", days_to_grow: 8, price: 50, sells_for: 180)
hot_pepper = Plant.create(name: "Hot Pepper", days_to_grow: 5, price: 40, sells_for: 90)
melon = Plant.create(name: "Melon", days_to_grow: 12, price: 110, sells_for: 350)
red_cabbage = Plant.create(name: "Red Cabbage", days_to_grow: 9, price: 90, sells_for: 260)
starfruit = Plant.create(name: "Starfruit", days_to_grow: 13, price: 450, sells_for: 1200)
wheat = Plant.create(name: "Wheat", days_to_grow: 2, price: 10, sells_for: 20)

jeff = Farmer.create(name: "jeff", abducted: true)
jacob = Farmer.create(name: "jacob")
